name: SocialMedia
description: Its a simple social media
version: 1.0.0

environment:
  sdk: '^3.2.0'
  
dependencies:
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'

